/** The primitives layer. Importing this module registers its tags. */
import './button/button'
import './icon-button/icon-button'
import './status-dot/status-dot'
import './skeleton/skeleton'
import './grid/grid'
import './grid-item/grid-item'
import './tile/tile'
import './badge/badge'
import './spinner/spinner'
import './progress-bar/progress-bar'
import './popover/popover'
import './tooltip/tooltip'

export { LintjeButton } from './button/button'
export type { ButtonSize, ButtonVariant } from './button/button'
export { LintjeIconButton } from './icon-button/icon-button'
export type { IconButtonVariant } from './icon-button/icon-button'
export { LintjeStatusDot, STATUS_LABEL } from './status-dot/status-dot'
export { LintjeSkeleton } from './skeleton/skeleton'
export { LintjeGrid } from './grid/grid'
export { LintjeGridItem } from './grid-item/grid-item'
export { LintjeGridItemElement, spanStyles } from './shared/grid-item-element'
export { LintjeTile } from './tile/tile'
export { LintjeBadge, badgeStyles, renderBadge } from './badge/badge'
export type { BadgeOptions, BadgeTone, BadgeVariant } from './badge/badge'
export { LintjeSpinner } from './spinner/spinner'
export type { SpinnerSize } from './spinner/spinner'
export { LintjeProgressBar } from './progress-bar/progress-bar'
export type { ProgressTone } from './progress-bar/progress-bar'
export { LintjePopover } from './popover/popover'
export { LintjeTooltip } from './tooltip/tooltip'
export { place } from './shared/place'
export type { Place, Placement } from './shared/place'
